### ISSUE TITLE
faces from popup.el

### ISSUE THREAD

**Issue by tsuu32** [akirak/mozc-posframe#2]
The faces `popup-face`, `popup-tip-face` and  `popup-summary-face` are defined in popup.el.

So candidates is not colored when emacs doesn't load popup.el.

**Comment by akirak** [comment]
I see. What should I use as the default values?

**Comment by tsuu32** [comment]
I think using the faces from mozc.el is better.
`mozc-cand-posframe-normal-face` -> `mozc-cand-overlay-odd-face` or `mozc-cand-overlay-even-face`
`mozc-cand-posframe-focused-face` -> `mozc-cand-overlay-focused-face`
`mozc-cand-posframe-footer-face` -> `mozc-cand-overlay-footer-face`

**Comment by akirak** [comment]
I don't like the colors. I've set some sensible colors instead.
