### ISSUE TITLE
Byte-compiling warning

### ISSUE THREAD

**Issue by tsuu32** [akirak/mozc-posframe#3]
新しいmozc-cand-posframeを試してみたところバイトコンパイル中にwarningが発生しました。
```
Warning (bytecomp): Unused lexical variable ‘posframe-height’
Warning (bytecomp): the function ‘s-pad-left’ is not known to be defined.
```

`posframe-height`をletでバインドしているのにどこでも使ってないというのと、s.elの関数を依存に追加していないのに使ってしまっているようです。

**Comment by akirak** [comment]
Thanks. I've fixed all the errors except for the following warning, which is unfixable for me:

> mozc-cand-posframe.el:5:57: warning: Use a non-snapshot version number for dependency on "mozc" if possible.

**Comment by tsuu32** [comment]
Thanks!
MELPAを見た限り、他のmozc依存のパッケージはどれも`(mozc "0")`としているようです。
https://melpa.org/#/?q=mozc

**Comment by akirak** [comment]
As far as I remember, `(mozc "0")` never vanishes the package-lint warning. None of those mozc-related packages on MELPA don't have package-lint run on CI. `(mozc "20180101.800")` is a valid specification, so I won't change it.
