### ISSUE TITLE
Posframe-delete-frame error

### ISSUE THREAD

**Issue by minorugh** [akirak/mozc-posframe#6]
Thank you for the wonderful package.

I've been getting the following error since posframe was updade to 20220110.422.

"posframe-delete-frame: Attempt to delete the sole visible or iconified frame"

**Comment by akirak** [comment]
I am no longer using this package myself, so it will take some time to reproduce the error. 

When do you encounter the error? Is it when the posframe is shown or is closed?

**Comment by minorugh** [comment]
Thank you for your reply.
An error is displayed when you start mozc and press the convert key to confirm. Then mozc hardens.

The code part below has been changed and if you replace this part, the error will disappear, but there seems to be other suspicious parts.

There is no problem with the old version of posframe ...

```emacs-lisp
(defun posframe-delete-frame (buffer-or-name)
  "Delete posframe pertaining to BUFFER-OR-NAME.
BUFFER-OR-NAME can be a buffer or a buffer name."
  (dolist (frame (frame-list))
    (let ((buffer-info (frame-parameter frame 'posframe-buffer))
          (buffer (get-buffer buffer-or-name)))
      (when (or (equal buffer-or-name (car buffer-info))
                (equal buffer-or-name (cdr buffer-info)))
        (when buffer
          (with-current-buffer buffer
            (dolist (timer '(posframe--refresh-timer
                             posframe--timeout-timer))
              (when (timerp timer)
                (cancel-timer timer)))))
        (delete-frame frame)))))

```

**Comment by akirak** [comment]
I have sent a PR (https://github.com/tumashu/posframe/pull/111). Please wait until he responds.

**Comment by akirak** [comment]
posframe has been updated. Could you see if the issue has been fixed?

**Comment by minorugh** [comment]
We apologize for the inconvenience. I completely confirmed the repair operation. I'm impressed. appreciate.

**Comment by akirak** [comment]
Thanks.
